version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/labdb
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      SECRET_KEY: your-secret-key-here-change-in-production
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  prometheus:
    image: prom/prometheus
    volumes:
      - ./devops/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
volumes:
  pgdata:
  minio-data:
